In [105]:
import sys
import os

# ajouter le dossier racine du projet
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

In [109]:
from importlib import reload
import src.data_loader
reload(src.data_loader)
from src.data_loader import load_dvf_data
from src.data_processing import clean_data

In [110]:
import pandas as pd

# charger le fichier CSV
df_raw = pd.read_csv("h:\Desktop\data_real_estate\dvf_2024.csv", sep="|")  # ou sep=";" selon ton fichier

C:\Users\Administrateur\AppData\Local\Temp\ipykernel_2532\85928657.py:4: DtypeWarning: Columns (18,23,24,26,28,30,31,33,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df_raw = pd.read_csv("../data/raw/dvf_2024.csv", sep="|")  # ou sep=";" selon ton fichier

In [111]:
# appeler la fonction de nettoyage
df_clean = clean_data(df_raw)

# vérifier le résultat
df_clean.head()
df_clean.info()

h:\Desktop\real-estate-price-prediction\src\data_processing.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Nombre pieces principales"].fillna(df["Nombre pieces principales"].median(), inplace=True)
h:\Desktop\real-estate-price-prediction\src\data_processing.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Surface terrain"].fillna(0, inplace=True)

<class 'pandas.core.frame.DataFrame'>
Index: 985249 entries, 3 to 3489148
Data columns (total 97 columns):
 #   Column                                               Non-Null Count   Dtype
---  ------                                               --------------   -----
 0   Valeur fonciere                                      985249 non-null  float64
 1   Surface reelle bati                                  985249 non-null  float64
 2   Nombre pieces principales                            985249 non-null  float64
 3   Surface terrain                                      985249 non-null  float64
 4   annee_mutation                                       342903 non-null  float64
 5   mois_mutation                                        342903 non-null  float64
 6   Type local_Local industriel. commercial ou assimilé  985249 non-null  bool
 7   Type local_Maison                                    985249 non-null  bool
 8   Code departement_10                                  985249 non-null  bool
 9   Code departement_11                                  985249 non-null  bool
 10  Code departement_12                                  985249 non-null  bool
 11  Code departement_13                                  985249 non-null  bool
 12  Code departement_14                                  985249 non-null  bool
 13  Code departement_15                                  985249 non-null  bool
 14  Code departement_16                                  985249 non-null  bool
 15  Code departement_17                                  985249 non-null  bool
 16  Code departement_18                                  985249 non-null  bool
 17  Code departement_19                                  985249 non-null  bool
 18  Code departement_20                                  985249 non-null  bool
 19  Code departement_21                                  985249 non-null  bool
 20  Code departement_22                                  985249 non-null  bool
 21  Code departement_23                                  985249 non-null  bool
 22  Code departement_24                                  985249 non-null  bool
 23  Code departement_25                                  985249 non-null  bool
 24  Code departement_26                                  985249 non-null  bool
 25  Code departement_27                                  985249 non-null  bool
 26  Code departement_28                                  985249 non-null  bool
 27  Code departement_29                                  985249 non-null  bool
 28  Code departement_30                                  985249 non-null  bool
 29  Code departement_31                                  985249 non-null  bool
 30  Code departement_32                                  985249 non-null  bool
 31  Code departement_33                                  985249 non-null  bool
 32  Code departement_34                                  985249 non-null  bool
 33  Code departement_35                                  985249 non-null  bool
 34  Code departement_36                                  985249 non-null  bool
 35  Code departement_37                                  985249 non-null  bool
 36  Code departement_38                                  985249 non-null  bool
 37  Code departement_39                                  985249 non-null  bool
 38  Code departement_40                                  985249 non-null  bool
 39  Code departement_41                                  985249 non-null  bool
 40  Code departement_42                                  985249 non-null  bool
 41  Code departement_43                                  985249 non-null  bool
 42  Code departement_44                                  985249 non-null  bool
 43  Code departement_45                                  985249 non-null  bool
 44  Code departement_46                                  985249 non-null  bool
 45  Code departement_47                                  985249 non-null  bool
 46  Code departement_48                                  985249 non-null  bool
 47  Code departement_49                                  985249 non-null  bool
 48  Code departement_50                                  985249 non-null  bool
 49  Code departement_51                                  985249 non-null  bool
 50  Code departement_52                                  985249 non-null  bool
 51  Code departement_53                                  985249 non-null  bool
 52  Code departement_54                                  985249 non-null  bool
 53  Code departement_55                                  985249 non-null  bool
 54  Code departement_56                                  985249 non-null  bool
 55  Code departement_57                                  985249 non-null  bool
 56  Code departement_58                                  985249 non-null  bool
 57  Code departement_59                                  985249 non-null  bool
 58  Code departement_60                                  985249 non-null  bool
 59  Code departement_61                                  985249 non-null  bool
 60  Code departement_62                                  985249 non-null  bool
 61  Code departement_63                                  985249 non-null  bool
 62  Code departement_64                                  985249 non-null  bool
 63  Code departement_65                                  985249 non-null  bool
 64  Code departement_66                                  985249 non-null  bool
 65  Code departement_67                                  985249 non-null  bool
 66  Code departement_68                                  985249 non-null  bool
 67  Code departement_69                                  985249 non-null  bool
 68  Code departement_70                                  985249 non-null  bool
 69  Code departement_71                                  985249 non-null  bool
 70  Code departement_72                                  985249 non-null  bool
 71  Code departement_73                                  985249 non-null  bool
 72  Code departement_74                                  985249 non-null  bool
 73  Code departement_75                                  985249 non-null  bool
 74  Code departement_76                                  985249 non-null  bool
 75  Code departement_77                                  985249 non-null  bool
 76  Code departement_78                                  985249 non-null  bool
 77  Code departement_79                                  985249 non-null  bool
 78  Code departement_80                                  985249 non-null  bool
 79  Code departement_81                                  985249 non-null  bool
 80  Code departement_82                                  985249 non-null  bool
 81  Code departement_83                                  985249 non-null  bool
 82  Code departement_84                                  985249 non-null  bool
 83  Code departement_85                                  985249 non-null  bool
 84  Code departement_86                                  985249 non-null  bool
 85  Code departement_87                                  985249 non-null  bool
 86  Code departement_88                                  985249 non-null  bool
 87  Code departement_89                                  985249 non-null  bool
 88  Code departement_90                                  985249 non-null  bool
 89  Code departement_91                                  985249 non-null  bool
 90  Code departement_92                                  985249 non-null  bool
 91  Code departement_93                                  985249 non-null  bool
 92  Code departement_94                                  985249 non-null  bool
 93  Code departement_95                                  985249 non-null  bool
 94  Code departement_96                                  985249 non-null  bool
 95  Code departement_97                                  985249 non-null  bool
 96  Code departement_98                                  985249 non-null  bool
dtypes: bool(91), float64(6)
memory usage: 138.1 MB

In [84]:
import pandas as pd
from src.data_loader import load_dvf_data

# chemin vers ton fichier téléchargé
file_path = "../data/raw/dvf_2024.csv"

df = load_dvf_data(file_path)

# voir les premières lignes
df.head()

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,...,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,02/01/2024,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,P,NaN,99.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,03/01/2024,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,S,NaN,115.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,08/01/2024,Vente,...,NaN,0,NaN,NaN,NaN,NaN,NaN,S,NaN,497.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,03/01/2024,Vente,...,NaN,2,2.0,Appartement,NaN,89.0,4.0,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,03/01/2024,Vente,...,NaN,1,3.0,Dépendance,NaN,0.0,0.0,NaN,NaN,NaN

In [85]:
df.columns

Index(['Identifiant de document', 'Reference document', '1 Articles CGI',
       '2 Articles CGI', '3 Articles CGI', '4 Articles CGI', '5 Articles CGI',
       'No disposition', 'Date mutation', 'Nature mutation', 'Valeur fonciere',
       'No voie', 'B/T/Q', 'Type de voie', 'Code voie', 'Voie', 'Code postal',
       'Commune', 'Code departement', 'Code commune', 'Prefixe de section',
       'Section', 'No plan', 'No Volume', '1er lot',
       'Surface Carrez du 1er lot', '2eme lot', 'Surface Carrez du 2eme lot',
       '3eme lot', 'Surface Carrez du 3eme lot', '4eme lot',
       'Surface Carrez du 4eme lot', '5eme lot', 'Surface Carrez du 5eme lot',
       'Nombre de lots', 'Code type local', 'Type local', 'Identifiant local',
       'Surface reelle bati', 'Nombre pieces principales', 'Nature culture',
       'Nature culture speciale', 'Surface terrain'],
      dtype='object')

In [86]:
df.describe()

,Identifiant de document,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,No voie,Code postal,Code commune,Prefixe de section,No plan,5eme lot,Nombre de lots,Code type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Surface terrain
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.489149e+06,2.157060e+06,3.466397e+06,3.489149e+06,170201.000000,3.489149e+06,7127.000000,3.489149e+06,2.006266e+06,0.0,2.003901e+06,2.003901e+06,2.411123e+06
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.236162e+00,6.591015e+02,5.005204e+04,2.060409e+02,433.055329,4.122547e+02,247.348955,4.232900e-01,2.280403e+00,NaN,6.556826e+01,1.724282e+00,3.111542e+03
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.448379e+00,1.947017e+03,2.748963e+04,1.665312e+02,315.710455,5.797546e+02,5643.207903,8.393400e-01,9.254353e-01,NaN,8.028068e+02,2.062316e+00,1.455585e+04
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+00,1.000000e+00,1.000000e+03,1.000000e+00,1.000000,1.000000e+00,2.000000,0.000000e+00,1.000000e+00,NaN,0.000000e+00,0.000000e+00,0.000000e+00
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+00,8.000000e+00,2.811000e+04,7.400000e+01,164.000000,8.400000e+01,7.000000,0.000000e+00,1.000000e+00,NaN,0.000000e+00,0.000000e+00,2.580000e+02
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+00,2.400000e+01,4.938000e+04,1.690000e+02,314.000000,2.210000e+02,20.000000,0.000000e+00,2.000000e+00,NaN,2.900000e+01,1.000000e+00,6.550000e+02
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000e+00,9.400000e+01,7.500700e+04,2.940000e+02,820.000000,5.060000e+02,57.000000,1.000000e+00,3.000000e+00,NaN,8.000000e+01,3.000000e+00,1.990000e+03
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.110000e+02,9.999000e+03,9.749000e+04,9.090000e+02,950.000000,8.399000e+03,242014.000000,2.360000e+02,4.000000e+00,NaN,5.934000e+05,1.980000e+02,7.700000e+06

In [87]:
df.isnull().sum()

Identifiant de document       3489149
Reference document            3489149
1 Articles CGI                3489149
2 Articles CGI                3489149
3 Articles CGI                3489149
4 Articles CGI                3489149
5 Articles CGI                3489149
No disposition                      0
Date mutation                       0
Nature mutation                     0
Valeur fonciere                 37382
No voie                       1332089
B/T/Q                         3337394
Type de voie                  1400643
Code voie                       22405
Voie                            22436
Code postal                     22752
Commune                             0
Code departement                    0
Code commune                        0
Prefixe de section            3318948
Section                            95
No plan                             0
No Volume                     3481087
1er lot                       2428557
Surface Carrez du 1er lot     3182238
2eme lot                      3169995
Surface Carrez du 2eme lot    3390384
3eme lot                      3433435
Surface Carrez du 3eme lot    3478084
4eme lot                      3471600
Surface Carrez du 4eme lot    3486603
5eme lot                      3482022
Surface Carrez du 5eme lot    3488385
Nombre de lots                      0
Code type local               1482883
Type local                    1482883
Identifiant local             3489149
Surface reelle bati           1485248
Nombre pieces principales     1485248
Nature culture                1078026
Nature culture speciale       3331316
Surface terrain               1078026
dtype: int64

In [88]:
df.shape

(3489149, 43)

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3489149 entries, 0 to 3489148
Data columns (total 43 columns):
 #   Column                      Dtype
---  ------                      -----
 0   Identifiant de document     float64
 1   Reference document          float64
 2   1 Articles CGI              float64
 3   2 Articles CGI              float64
 4   3 Articles CGI              float64
 5   4 Articles CGI              float64
 6   5 Articles CGI              float64
 7   No disposition              int64
 8   Date mutation               object
 9   Nature mutation             object
 10  Valeur fonciere             object
 11  No voie                     float64
 12  B/T/Q                       object
 13  Type de voie                object
 14  Code voie                   object
 15  Voie                        object
 16  Code postal                 float64
 17  Commune                     object
 18  Code departement            object
 19  Code commune                int64
 20  Prefixe de section          float64
 21  Section                     object
 22  No plan                     int64
 23  No Volume                   object
 24  1er lot                     object
 25  Surface Carrez du 1er lot   object
 26  2eme lot                    object
 27  Surface Carrez du 2eme lot  object
 28  3eme lot                    object
 29  Surface Carrez du 3eme lot  object
 30  4eme lot                    object
 31  Surface Carrez du 4eme lot  object
 32  5eme lot                    float64
 33  Surface Carrez du 5eme lot  object
 34  Nombre de lots              int64
 35  Code type local             float64
 36  Type local                  object
 37  Identifiant local           float64
 38  Surface reelle bati         float64
 39  Nombre pieces principales   float64
 40  Nature culture              object
 41  Nature culture speciale     object
 42  Surface terrain             float64
dtypes: float64(16), int64(4), object(23)
memory usage: 1.1+ GB

In [90]:
df.shape

(3489149, 43)

In [91]:
df["Valeur fonciere"].head(20)

0        346,50
1      10000,00
2     249000,00
3     329500,00
4     329500,00
5     329500,00
6     329500,00
7      20000,00
8      20000,00
9      20000,00
10     20000,00
11     20000,00
12     20000,00
13     20000,00
14     20000,00
15     20000,00
16     20000,00
17     20000,00
18     20000,00
19     20000,00
Name: Valeur fonciere, dtype: object

In [92]:
df["Valeur fonciere"] = df["Valeur fonciere"].str.replace(",", ".")
df["Valeur fonciere"] = pd.to_numeric(df["Valeur fonciere"], errors="coerce")

In [93]:
df = df[df["Valeur fonciere"].notna()]
df = df[df["Surface reelle bati"].notna()]
df = df[df["Surface reelle bati"] > 0]
df = df[df["Valeur fonciere"] > 10000]

In [94]:
len(df)

1087395

In [95]:
df["prix_m2"] = df["Valeur fonciere"] / df["Surface reelle bati"]
df = df[df["prix_m2"] < 20000]  # valeurs très élevées
df = df[df["prix_m2"] > 500]    # valeurs très basses

In [96]:
len(df)

988578

In [97]:
df.isnull().sum()

Identifiant de document       988578
Reference document            988578
1 Articles CGI                988578
2 Articles CGI                988578
3 Articles CGI                988578
4 Articles CGI                988578
5 Articles CGI                988578
No disposition                     0
Date mutation                      0
Nature mutation                    0
Valeur fonciere                    0
No voie                         7176
B/T/Q                         922237
Type de voie                   98681
Code voie                          0
Voie                               4
Code postal                       75
Commune                            0
Code departement                   0
Code commune                       0
Prefixe de section            944802
Section                           41
No plan                            0
No Volume                     988578
1er lot                       600339
Surface Carrez du 1er lot     788026
2eme lot                      834315
Surface Carrez du 2eme lot    940255
3eme lot                      964549
Surface Carrez du 3eme lot    983872
4eme lot                      980651
Surface Carrez du 4eme lot    987455
5eme lot                      985114
Surface Carrez du 5eme lot    988214
Nombre de lots                     0
Code type local                    0
Type local                         0
Identifiant local             988578
Surface reelle bati                0
Nombre pieces principales          0
Nature culture                393396
Nature culture speciale       971827
Surface terrain               393396
prix_m2                            0
dtype: int64

In [98]:
cols_to_drop = ["B/T/Q", "Prefixe de section", "1er lot", "No Volume", "Nature culture", "Nature culture speciale", "Identifiant de document","Reference document","Identifiant local","Surface terrain"]
df = df.drop(columns=cols_to_drop)

In [99]:
df.isnull().sum()

1 Articles CGI                988578
2 Articles CGI                988578
3 Articles CGI                988578
4 Articles CGI                988578
5 Articles CGI                988578
No disposition                     0
Date mutation                      0
Nature mutation                    0
Valeur fonciere                    0
No voie                         7176
Type de voie                   98681
Code voie                          0
Voie                               4
Code postal                       75
Commune                            0
Code departement                   0
Code commune                       0
Section                           41
No plan                            0
Surface Carrez du 1er lot     788026
2eme lot                      834315
Surface Carrez du 2eme lot    940255
3eme lot                      964549
Surface Carrez du 3eme lot    983872
4eme lot                      980651
Surface Carrez du 4eme lot    987455
5eme lot                      985114
Surface Carrez du 5eme lot    988214
Nombre de lots                     0
Code type local                    0
Type local                         0
Surface reelle bati                0
Nombre pieces principales          0
prix_m2                            0
dtype: int64

In [100]:
df["Type de voie"] = df["Type de voie"].fillna("Autre")
df["Code postal"] = df["Code postal"].fillna(0)  # ou '00000'

In [101]:
df.isnull().sum()

1 Articles CGI                988578
2 Articles CGI                988578
3 Articles CGI                988578
4 Articles CGI                988578
5 Articles CGI                988578
No disposition                     0
Date mutation                      0
Nature mutation                    0
Valeur fonciere                    0
No voie                         7176
Type de voie                       0
Code voie                          0
Voie                               4
Code postal                        0
Commune                            0
Code departement                   0
Code commune                       0
Section                           41
No plan                            0
Surface Carrez du 1er lot     788026
2eme lot                      834315
Surface Carrez du 2eme lot    940255
3eme lot                      964549
Surface Carrez du 3eme lot    983872
4eme lot                      980651
Surface Carrez du 4eme lot    987455
5eme lot                      985114
Surface Carrez du 5eme lot    988214
Nombre de lots                     0
Code type local                    0
Type local                         0
Surface reelle bati                0
Nombre pieces principales          0
prix_m2                            0
dtype: int64

In [102]:
df = df.drop(columns=[col for col in df.columns if "Articles CGI" in col])

In [103]:
lots_cols = [col for col in df.columns if "Surface Carrez" in col or "lot" in col]
df = df.drop(columns=lots_cols)

In [104]:
df.isnull().sum()

No disposition                  0
Date mutation                   0
Nature mutation                 0
Valeur fonciere                 0
No voie                      7176
Type de voie                    0
Code voie                       0
Voie                            4
Code postal                     0
Commune                         0
Code departement                0
Code commune                    0
Section                        41
No plan                         0
Code type local                 0
Type local                      0
Surface reelle bati             0
Nombre pieces principales       0
prix_m2                         0
dtype: int64